spring:
  application:
    name: backend-adocao


  datasource:
    url: jdbc:postgresql://gerenciadorapi-database.ct8wo6og4nao.sa-east-1.rds.amazonaws.com/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
